server:
  port: 8081
spring:
  application:
    name: Acount
  data:
    mongodb:
      database: baseMongo
      host: localhost
      port: 27017
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
