server:
  port: 8084
spring:
  application:
    name: Movements
  data:
    mongodb:
      database: baseMongo
      host: monguito
      port: 27017
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka